export const FETCH_DATA = 'EMPLOYER_PANEL.FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'EMPLOYER_PANEL.FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'EMPLOYER_PANEL.FETCH_DATA_FAILED';

export const CLEAR_DATA = 'EMPLOYER_PANEL.CLEAR_DATA';

export const SET_PLACE_ID = 'EMPLOYER_PANEL.SET_PLACE_ID';

export const SET_BACK_PANEL = 'EMPLOYER_PANEL.SET_BACK_PANEL';
