export const FETCH_DATA = 'VACANCY_LIST_PANEL.FETCH_DATA';
export const FETCH_DATA_SUCCESS = 'VACANCY_LIST_PANEL.FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILED = 'VACANCY_LIST_PANEL.FETCH_DATA_FAILED';

export const FETCH_DATA_MORE = 'VACANCY_LIST_PANEL.FETCH_DATA_MORE';
export const FETCH_DATA_MORE_SUCCESS = 'VACANCY_LIST_PANEL.FETCH_DATA_MORE_SUCCESS';
export const FETCH_DATA_MORE_FAILED = 'VACANCY_LIST_PANEL.FETCH_DATA_MORE_FAILED';

export const SET_IS_CAN_FETCH_DATA = 'VACANCY_LIST_PANEL.SET_IS_CAN_FETCH_DATA';
export const SET_PAGE = 'VACANCY_LIST_PANEL.SET_PAGE';
